version: "3.8"

services:
  django1:
    build: .
    restart: on-failure:10
    ports:
      - "8000:8000"
    env_file:
      - ./cloud_computing/.env
    links:
      - postgres_db1
    depends_on:
      - postgres_db1
    volumes:
    - pdaj_data:/usr/src
    
    
  postgres_db1:
    image: postgres
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1111
      - POSTGRES_DB=cloud1  

volumes:
  pdaj_data: