# Generated by Django 4.0.1 on 2022-01-14 01:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('date_made', models.DateTimeField(default=django.utils.timezone.now)),
                ('healthy', models.BooleanField(default=False)),
            ],
        ),
    ]
